### ISSUE TITLE
Notification emails don't trigger login prompt

### ISSUE THREAD

**Issue by BarelyAPrincess** [PenoaksDevOps/HolyWorlds-Issues#10]
# User Submitted Issue

**Username:** kingjon
**E-mail Address:** kingjon3377@gmail.com

**Descripe The Issue:**
When I open the (first) link in a "topic notification" or "forum post notification" email, in a browser where my HW login session has expired (if I was logged in at all), I expect to be prompted to log in to see the thread. This no longer happens. (And while the "log in to see this" prompt is an annoyance, I want my view to be recorded as *me* so I'll get another email on any further activity.)

**Steps to Reproduce:**
Open any topic-notification link, that's not to a thread in a *room* that's limited to logged-in users, in a "private browsing" window.

**URL:** https://holyworlds.org/viewtopic.php?f=35&t=9615&p=206131&e=206131

**Comment by BarelyAPrincess** [comment]
It would seem notification e-mails were broken since the update, so I can only assume you were using an e-mail before the upgrade which might explain the problem. I'll look into this once someone can confirm the problem still exists with newer notification e-mails.

**Comment by kingjon3377** [comment]
A more recent notification email does indeed prompt me (in my testing just now), as does one from back in April, so it looks like some change in the meantime fixed it.

**Comment by BarelyAPrincess** [comment]
Okay, good. I had a feeling it was something simple since this would have involved phpBB at its core.
