### ISSUE TITLE
Notification emails not being generated

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#13]
I haven't gotten a "forum post notification" email since May 14, and while the forum has been very quiet lately, I know that posts have been made in at least one forum I'm subscribed to (namely Quests) in that time, including after my most recent visit to that forum before today. (I haven't gotten a "topic reply notification" email either, but while I expect that would be affected by the same cause, I don't think any thread I'm subscribed to has seen any replies lately.)

**Comment by kingjon3377** [comment]
I can now confirm that I haven't gotten any topic notification emails when I should have gotten at least one.  (And I've checked my "spam" box often enough, including again just now, to be sure the notification emails weren't *just* getting misfiled there.)

I seem to recall, before the Penoaks acquisition, Gmail flagging HW notification emails as possible spam due to something like some security standard not being followed, or something like that. Perhaps Gmail's security requirements have been raised to the point that this results in rejection or silent drops instead of filing messages as spam?

**Comment by BarelyAPrincess** [comment]
Sorry for the delay. I've finally sat down and sorted out the error. They should be fixed now.
