### ISSUE TITLE
Chat tries & fails to load missing avatar

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#14]
When the chat room contains a message from a user who has not selected an avatar image, the header of that message tries to display that user's avatar anyway, which ends up showing as the "image failed to load" icon. (Instead of a JPEG or PNG image, it returns the string "The user avatar does not exist!".) I would expect to see some sort of placeholder (either a static "no-avatar-defined" image or something randomly generated, like Gravatar's "wavatars").

**Comment by BarelyAPrincess** [comment]
Fixed! There was also an issue with resolving every other avatar.
