### ISSUE TITLE
Can't filter members list by initial letter

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#16]
On [the "Members" [list] page](https://holyworlds.org/memberlist.php), there's a combo-box that's supposed to let me look at just those members whose names begin with some letter (after the text "Username begins with", and followed by a button "Display"), but it doesn't have any letters in it.

**Comment by BarelyAPrincess** [comment]
Fixed! Turns out phpBB removed that feature from the latest release and the DarkFantasy template still expected it. Modded the template to make it work once again.
