### ISSUE TITLE
Domain has expired

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#30]
The holyworlds.org has, as of today, started resolving to a domain-parking site.

![domain expired message](https://user-images.githubusercontent.com/1522278/75111975-74a8bb00-560d-11ea-849f-4e73330feacf.png)

**Comment by aidan-casey** [comment]
It’s been offline since last Thursday. I notified Rachel, but have not heard from her yet.

**Comment by kingjon3377** [comment]
Shows how infrequently I check it; I only noticed it being down on Friday, and after giving it overnight was going to check one last time before reporting *that*, only to find the "domain has expired" page instead. 

But the domain now shows the proper site and that site is back up. Should this just be closed now?

**Comment by aidan-casey** [comment]
Yes, it should. Rachel confirmed they had it renewed.
