### ISSUE TITLE
DNS registration lapsed

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#33]
When I tried to visit HW today (to reread, and check for an update on, the "exciting changes ahead!" notice that had replaced the main page the last time I visited, a week or two ago) I found a domain parking site instead. (Showing ads for skin condition treatments, of all things ...) Looks like the domain name registration has been allowed to lapse.

**Comment by BarelyAPrincess** [comment]
I had been having an issue not receiving the renewal e-mails from my domain registrar, so I became unaware of when a domain was up for renewal. The good news is I got why I wasn't getting those e-mails fixed and the domain renewed, so this shouldn't ever happen again.

As for the "exciting changes ahead" announcement, there are plans in place to begin expanding into new territories for the HolyWorlds imprint. Foremost, there are plans to begin producing a series of books that highlight the wonders of the community over the past ten years. Any money made from those sales will be put forward to build the website out to give members access to the HolyWorlds brand/imprint for their own publishing project. There are many ideas coming and it could take a bit of time.
